apiVersion: apps/v1
kind: Deployment
metadata:
  name: javacode
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: tomcat
        image: tomcat
